/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Content: typeof import('./components/ContentView.vue')['default']
    ContentLine: typeof import('./components/ContentLine.vue')['default']
    ContentView: typeof import('./components/ContentView.vue')['default']
    MainView: typeof import('./components/MainView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
